
### Смена пароля юзера
PUT /api/changepassword/ HTTP/1.1
Host: {{host}}
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YmIzZDQxMzBlMjU4NDI1OTg1YzljYzciLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE1Mzg1OTIzNjQsImV4cCI6MTUzODU5MzU2NCwic3ViIjoiYWNjZXNzIn0.uyEGgEmDm6tFApugl6_J28ABOyV3ETLgpXdXw_ueWlCym2xq4v-YVcNouUFAgc6iUclY_fdWK9ZfYZGnbul7Sg
Content-Type: application/json

{
	"newPassword": "000"
}

