
###
POST /api/game/ HTTP/1.1
Host: {{host}}
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YmJjZGZiNTAzOWQ0ODIyMjAyY2M1YTgiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE1NDAxMjcxODgsImV4cCI6MTU0MDEzNDM4OCwic3ViIjoiYWNjZXNzIn0.nOZRmrZyK2RuUrqekZb2BqQLs_aL4ryZ07lzhOSLUD4gCJrWyDBM_gDw6dWxN_GLpo43lsczqcq0czbfl6XrSg
Content-Type: application/json

{
	"userColor": "white"
	, "boardSize": "8"
	, "level": "light"
	, "mode": "classic"
}

###
PUT /api/game HTTP/1.1
Host: {{host}}
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YmJjZGZiNTAzOWQ0ODIyMjAyY2M1YTgiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE1NDAxMjcxODgsImV4cCI6MTU0MDEzNDM4OCwic3ViIjoiYWNjZXNzIn0.nOZRmrZyK2RuUrqekZb2BqQLs_aL4ryZ07lzhOSLUD4gCJrWyDBM_gDw6dWxN_GLpo43lsczqcq0czbfl6XrSg
Content-Type: application/json

{
	"movesCount": "3"
	, "totalOfGame": "st"
}
