
###
POST /api/game/ HTTP/1.1
Host: {{host}}
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YmJjZGZiNTAzOWQ0ODIyMjAyY2M1YTgiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE1NDAwNjU1MTgsImV4cCI6MTU0MDA3MjcxOCwic3ViIjoiYWNjZXNzIn0.7OnDmFC0Kx5Ul2fZ36njH1_4xPT3XB5P_-9TSrl8_zz51PA8edLNBkdg_JQdycnJ7Vf8cmx7Y6P0NDXclDI28w
Content-Type: application/json

{
	"userColor": "white"
	, "boardSize": "8"
	, "level": "light"
	, "mode": "classic"
}

###
PUT /api/game HTTP/1.1
Host: {{host}}
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YmJjZGZiNTAzOWQ0ODIyMjAyY2M1YTgiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE1NDAwNjU1MTgsImV4cCI6MTU0MDA3MjcxOCwic3ViIjoiYWNjZXNzIn0.7OnDmFC0Kx5Ul2fZ36njH1_4xPT3XB5P_-9TSrl8_zz51PA8edLNBkdg_JQdycnJ7Vf8cmx7Y6P0NDXclDI28w
Content-Type: application/json

{
	"movesCount": "3"
	, "totalOfGame": "st"
}
