
###
GET /api/lkUserData/ HTTP/1.1
Host: {{host}}
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YmJjZGZiNTAzOWQ0ODIyMjAyY2M1YTgiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE1NDAyMzQ4MTcsImV4cCI6MTU0MDI0MjAxNywic3ViIjoiYWNjZXNzIn0.fLvoR1RwPiDuF1p9LDj6Sqf2wRiDt4B9Lbo82H9jF3NK0doD9APc1Re14wu6tVZh5GUGevh1WoqNnr2DGTH4Jg