

###
POST /api/refreshtokens/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YmIzZDQxMzBlMjU4NDI1OTg1YzljYzciLCJpYXQiOjE1Mzg2NDc5NTMsImV4cCI6MTUzODY1MTU1Mywic3ViIjoicmVmcmVzaCJ9.5ysQoplUMPIfIfDMw_bn_4ogOnpOkKWtBmWvSWN1u1HcNVmTpIz7zrFJyppLjjZ24nApCU32jOAXQxbegb0XkQ"
}
