
###
GET /api/registration/ HTTP/1.1
Host: {{host}}

###
POST /api/registration/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"login": "sss9"
	, "email": "sss9"
	, "password": "111"
	, "firstName": "Vika"
}

###
PUT /api/registration/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"login": "qqqWWW"
	, "email": "q1222"
	, "password": "333"
}

###
DELETE /api/registration/ HTTP/1.1
Host: {{host}}