
###
GET /api/test/ HTTP/1.1
Host: {{host}}

###
POST /api/test/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"title": "first"
	, "color": "red"
}

###
PUT /api/test/5b9952892b96c72df0310331 HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"title": "second"
	, "color": "grey"
}

###
DELETE /api/test/5b99546120f7c02bd834645e HTTP/1.1
Host: {{host}}