
###
GET /api/test/ HTTP/1.1
Host: {{host}}

###
POST /api/test/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"title": "first"
	, "color": "red"
}

###
PUT /api/test/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "sportrank": {
        "id": 4
        , "displayName": "Художественная гимнастика"
    }
}

###
DELETE /api/test/5b994ae5d38ec017d0d7644c HTTP/1.1
Host: {{host}}