
###
GET /api/user/ HTTP/1.1
Host: {{host}}

###
POST /api/user/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"login": "aaa"
	, "email": "q1"
	, "password": "123"
}

###
PUT /api/user/5babbb4f65d1e624acdce3e0 HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"login": "qqqWWW"
	, "email": "q1222"
	, "password": "333"
}

###
DELETE /api/user/5babae96140d2f2b002f772f HTTP/1.1
Host: {{host}}